### ISSUE TITLE
 ./node_modules/angular2-google-login/index.ts

### ISSUE THREAD

**Issue by gns088** [rudrakshpathak/angular2-google-login#8]
Module build failed: Error: /var/www/html/Project/Project_angular2/node_modules/angular2-google-login/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/var/www/html/CEP/CEP_angular2/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:653:23)
    at plugin.done.then (/var/www/html/CEP/CEP_angular2/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
 @ ./src/app/featureModules/authentication/login/login.component.ts 23:30-62
 @ ./src/app/featureModules/authentication/authentication.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by vocariz** [comment]
Same issue here

**Comment by IamMayankThakur** [comment]
ERROR in ./node_modules/angular2-google-login/index.ts
Module build failed: Error: /home/mayank/GMR/gmr-web/node_modules/angular2-google-login/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/mayank/GMR/gmr-web/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/home/mayank/GMR/gmr-web/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)


Similar Issue
